Self Referee section
jbx-protocol/juice-defifa-interface pull request #4
Opened 2022-10-19 13:22 UTC by devianyeth

2022-10-19 18:24 UTC, NakedFool requested changes
Very well done @devianyeth !

Just a few minor changes and we are good to push 🍻

2022-10-19 18:24 UTC, NakedFool commented on src/components/SelfReferee/index.tsx
> +    <>
we shouldn't wrap <Content/> here :)

2022-10-19 18:24 UTC, NakedFool commented on src/components/SelfReferee/index.tsx
> +      <Content title="Self-Refereeing">
we can add [work in progress] here

2022-10-19 18:24 UTC, NakedFool commented on src/components/SelfReferee/index.tsx
> +            matches these results.
**these results** has an underline, you can wrap it with a span! :)

2022-10-19 18:24 UTC, NakedFool commented on src/components/SelfReferee/index.tsx
> +          <Button onClick={() => {}} size="big" color="#736B6F">
you can remove this button for now,  it is ok if we show only Queue button above for now

2022-10-19 19:31 UTC, NakedFool commented on src/components/SelfReferee/index.tsx
> +            matches these results.
One more thing, all paragraphs in self-referee section should have `font-weight: 500`

2022-10-20 06:26 UTC, devianyeth commented
@NakedFool, I've made the changes

2022-10-20 08:57 UTC, merged